---
env:
  global:
    - CC_TEST_REPORTER_ID=fec34310f03fd2cc767a85fa23d5102f3dca67b9cc967a48d9940027731394e8
sudo: false
language: ruby
cache:
  directories:
   - gemfiles/vendor/bundle
   - /home/travis/.rvm/
services: docker
jobs:
  include:
    - stage: Integration Tests
      script: |
        docker run -d -p 6379:6379 redislabs/redisearch:1.6.1 --protected-mode no --loadmodule /usr/lib/redis/modules/redisearch.so
        bundle exec rake test:integration
      rvm: 2.6
      gemfile: Gemfile
      name: RediSearch 1.6.1
    - stage: Integration Tests
      script: |
        docker run -d -p 6379:6379 redislabs/redisearch:1.4.13 --protected-mode no --loadmodule /usr/lib/redis/modules/redisearch.so
        bundle exec rake test:integration
      rvm: 2.6
      gemfile: Gemfile
      name: RediSearch 1.4.13
    - stage: Integration Tests
      script: |
        docker run -d -p 6379:6379 redislabs/redisearch:1.4.12 --protected-mode no --loadmodule /usr/lib/redis/modules/redisearch.so
        bundle exec rake test:integration
      rvm: 2.6
      gemfile: Gemfile
      name: RediSearch 1.4.12
    - stage: Integration Tests
      script: |
        docker run -d -p 6379:6379 redislabs/redisearch:1.4.11 --protected-mode no --loadmodule /usr/lib/redis/modules/redisearch.so
        bundle exec rake test:integration
      rvm: 2.6
      gemfile: Gemfile
      name: RediSearch 1.4.11
    - stage: Integration Tests
      script: |
        docker run -d -p 6379:6379 redislabs/redisearch:1.4.10 --protected-mode no --loadmodule /usr/lib/redis/modules/redisearch.so
        bundle exec rake test:integration
      rvm: 2.6
      gemfile: Gemfile
      name: RediSearch 1.4.10
    - stage: Unit Tests
      script: bundle exec rake test:unit
      rvm: ruby-head
      gemfile: Gemfile
      name: Ruby head and Rails 6.0
    - stage: Unit Tests
      script: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
        bundle exec rake test:unit
        if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
      rvm: 2.6
      gemfile: Gemfile
      name: Ruby 2.6 and Rails 6.0
    - stage: Unit Tests
      script: bundle exec rake test:unit
      rvm: 2.6
      gemfile: gemfiles/activerecord_52.gemfile
      name: Ruby 2.6 and Rails 5.2
    - stage: Unit Tests
      script: bundle exec rake test:unit
      rvm: 2.6
      gemfile: gemfiles/activerecord_51.gemfile
      name: Ruby 2.6 and Rails 5.1
    - stage: Unit Tests
      script: bundle exec rake test:unit
      rvm: 2.5
      gemfile: Gemfile
      name: Ruby 2.5 and Rails 6.0
    - stage: Lint
      script: bundle exec rubocop --config=./.rubocop.yml
      rvm: 2.6
      name: Rubocop
